tasks:
  - init: |
      npm install && npm run build
      sudo apt-get update
      sudo apt-get install -y xvfb
    command: |
      # Start Xvfb
      export DISPLAY=:99
      nohup Xvfb :99 -screen 0 1280x1024x24 &
      # Start the application
      npm run start
